version: '3'

services:
  db-mongo:
    image: mongo:3.6-jessie
    container_name: mongo
    volumes:
      # - db-notes-mongo:/data/db
      - ./mongod.conf:/etc/mongod.conf
    ports:
     - "27017:27017"
    command: mongod --auth -f "/etc/mongod.conf" --bind_ip_all
